# Gradle JVM Arguments
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-17.0.19.10-hotspot

# Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

# Mod Properties
mod_id=aetasferreamod
mod_name=Aetas Ferrea Mod
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.aetasferrea.aetasferreamod
mod_authors=Bleckwolf25
mod_description=Hardcore realism core that overhauls Minecraft's combat physics, armor weight mechanics, and equipment traits for a brutal medieval survival experience.